apiVersion: v1
kind: Service
metadata:
  name: proxygram-server
  labels:
    app: proxygram-server
spec:
  selector:
    app: proxygram-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
