apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proxygram-server
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: server/k8s
    repoURL: https://github.com/proxy-gram/proxygram.git
    targetRevision: HEAD
