---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCz+k5zlzatklCpYYKSGXiRAly1cflQX8h54JBxDcd3jSahagEPQbDdyvuu/DWiUgkYhImlF8gFm1wOrcHNUVRwL0NxOCn/k9whnHYNz89M4fvrnkc4UX6JsX1HPTyqT29cv64gDbYYHXAuSS4uD1zCxdbKNZsSq4j+2qIKc7OjFEZRsd9JYSrsY7LAgtet7liXfY1bqn0EvXIpCX6LQaC48X1YVq8g1+nYvYKUqzmukyfihLiMcLSkkxGq3dr8mIDvou3nVbmxc8y7oMYLagZTQuwC8AqtwORHXvee2V7AKcoBemtnvJKBk2B9F6OTRmg2X9Q3iJ6nDgMQmJD9dWxa4jrPvobSafheati+Doh9eQYpJzOmVSFbo602+Sl/XpxaYKCIK5Hun5VH535ZZhpH3KSxhALkQv1GdwfGJ/tZsaCIkevEpZH3TVh8DzHipGW5W6CWRxqXxhwRkRtnz1U8Gk7/p9OF1wDvVDR70b60+5Gqj9ypofqOsdIaiv0EA+iBLR8s3drUVC1rj387gEpYKOktYrAggEYxGcJGiSl+Mzq/08tFr/HjGek/H62L8ZE5aNxz4KOtnRkZRS45fMYO4Cxq37dwxphX5JNZVfbImDLEv572DGoQ+TwRtvRN1++AuvRfGX6oR7kv5Lm4et/B+f55TTruIFTqnQtSaL413lNl1rh/vQ+OYRDL0p5xPs6e17kd2vJddaCmXyNl+RwYIApLvuhpC1bhJQiTVV4o3z6doUZ99S9i
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
