---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCK9DRHSxrLFrNBXGtdW9sdYPH3CswVmJwO6R2YT96H5A7PIEFapUeNJHr8jvGlOm4V5YC2AZQ+xOhwkp/Z5Tbl9aMS6da+dwXD6GsyPTHI2qFq/YJ9t0Qe2W9eHpa02JfdUm8l8Ilf9xHYuJFwxSXYWOIELNbbCSnlP1MY9RJ4JcfBQw/QEyJAYYXrLwJNC7m7/K2p37CFBNR1JM3hOcMBSQLcrNCSmyYZIeCLkf9XFP/4bPFl5G39Urxuh5IAhjMJLIRxbTfvLKR9HNlreK0l7VLLHypW4VNMPKy1hhVVDSitUwP3fGRf6aXsIzkYcYz3MyaYXLfwAN94oi+DfGPqbNvO++svbV9EXN+qGzZFHWlZuZ/AqGpQzLWXPs6dtnjXHKmilKiGfZT9HGMfbLlLQ5hdHeZ+M9x36SjYdxbg/hx+Fcg+IA6Ow9ZQSMwsh0JC/Zkfx7ocdR8Nzsb/Eu20sWwKeAAvUPUWx8KlZkf9qjwGiQFOI3IfPh4kZr8KGQrIMGUCdoX+NIWBrsNBDeQQPnuKb0AD6ocz2N5z8CLUMFxJ5Blmoqe7pI8pCc8F51FyRA37vK7NcqTSTSu7D7YPIbKbNihRLPEd2bHDyY6Iy92YiMb26chWe+p23A1885iUYMtjRDT4nBgNZjmD8B/TwdTT3PNADiN6SRSfVhKzHfL77tsOWRdt58u0Ap/uFC4sAqLoCbC8LuDR0X44yd18FXSkyMHM/hC382+xCRr9NyEUIQIEcnq/
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
