apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cf-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: omics42@gmail.com
    privateKeySecretRef:
      name: letsencrypt-microk8s
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
