---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-login-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCmWcvODYv8W5Q/Ca3BNY+RSMg05+6wu4qWkFQ3IvRnMC0yxhlT9nL5uZEaUUncOigwYKQtH0IkgwCutGtBo3hDOjkHhFSIHJRr3rub7V35eHkDvLEqmnSV0P2bi0REKqaJlfbhWwLX0G+u1UtJmwJlKN6kWFOSVX7Cj+PsbA0FhymjzzYq8Y00wSGovsHBL+qDdZMV90vv38Ky+yggWmYJO6qTxfN1pZL3TakWovnPNGN5N/xG/OunMgqi2C/QwTj/qH8sB9yIEqjvBejiQQm/e7Gnx4n8N27icLvZgb9OqZlsN2mE4PxA+UNYerRjN/38hI/Cqf7ofVCLVaN3joMLWwx7rKxi+lTqBrZfGMgxjmvV9NKqtuvAS3Y0RmtjysMXP7QK3ItStNlfGi/qrWwJ3MmfxoTOUztFWbJDTVtGcgMZsh+I4NJ1oj7FwxJOZQPAAUW4WNjI2H+qGpWEN+PSGeAXS1pUc3gOVkip/dLk5MOS/GtRuXRA8uHTCFwJPLdIjpjc9Z/Ba4sjmSSXCE9vmhHwsjjFcVESPJnJpc17lbkqUxTrUCH/LNH0wZJI0bQD3ad6a9aQEFfBeq5RhkIxQOp/hTdclnnYPBbQ24Hd8CQA9g/674aYrgix8XqZyftmv82Se2yCUiOnDzCwexcoa5vwgfvDNgwQzSQ7JE6EvPJ4yYCMWXDd64p5Epc1rPrVbJ/zmbFQg3jnOr5sCvB00oOTtejVb3tqS7k1juBtgmAd5z9X60elwFGOsMbY6/JsoQwqQQCs3VCWOhWg+oAL7x3SehTNY1loSUPG4lkWRoYRGtPeGNgy39r746Oba1bcKLrWxVWF04Kk6vEfYbKLGmLmLlB3qJ3g2ePsweghamF/lZAKEOfmY7pjKLGE78KmfplcfM/DKURTL6l5WvZA/F0KpGlsitNjydl3NucaWUoxTay/JzlSTdjDzkQWPyICKWolShqakK5RUq4g23VJ
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-login-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
