name: tag.yml
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build-with-docker-engine:
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: before_script
        run: |
          TAG=$(echo $GITHUB_REF | cut -d'/' -f3)
          PACKAGE_VERSION=$(echo $TAG | cut -d'@' -f2)
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/

      - name: 'Install Dependencies'
        run: yarn

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: master

      - name: 'Build images'
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
          INPUT_TAGS: type=raw,value=${{ env.PACKAGE_VERSION }}
          NX_NO_CLOUD: true
          NPM_CONFIG_PROVENANCE: true
        run: npx nx release publish

      - name: Update k8s deployment
        run: |
          yarn tsx ./scripts/update-image-version.ts

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "chore(release): release v${{ env.PACKAGE_VERSION }}"
          commit-message: "chore(release): release v${{ env.PACKAGE_VERSION }}"
          base: master
          token: ${{ secrets.GH_PAT }}
          delete-branch: true
          branch: "chore/release-v${{ env.PACKAGE_VERSION }}"

